Fix build on FreeBSD
Build on FreeBSD fails with:

  CC       net.o
net.c:317:25: error: variable has incomplete type 'struct sockaddr_in6'
    struct sockaddr_in6 sa6;
                        ^
net.c:317:12: note: forward declaration of 'struct sockaddr_in6'
    struct sockaddr_in6 sa6;
           ^
net.c:318:24: error: variable has incomplete type 'struct sockaddr_in'
    struct sockaddr_in sa4;
                       ^
net.c:318:12: note: forward declaration of 'struct sockaddr_in'
    struct sockaddr_in sa4;
           ^
2 errors generated.

Need to include <netinet/in.h> to fix that.